### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by SeungHwanKimSKKU** [chaht01/Co2L#2]
Hello.

I've shocked about your paper's result.

So I want to try your code, but I could not get the result in your paper alike.

Unfortunately, I've runing your repo, I've get Nan of the loss.

Could you tell me why I get the Nan of loss value? and How to get the result what in your paper?

Thank you

**Comment by chaht01** [comment]
Hello. Thanks for your interest in my paper. 
We developed Co^2L based on Supervised Contrastive Learning codes ([link](https://github.com/HobbitLong/SupContrast)).
In my experience, apex can causes NaN loss though your code is running without unexpected termination.
You can also check many issues on SupCon [repo](https://github.com/HobbitLong/SupContrast) which might helps your problems. 
I recommend you to run the above repo(SupCon) first to see libraries are installed well, and then run our code.
